/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibal_yazid_saad.View;

import bibal_yazid_saad.Connection.DbInteraction;
import bibal_yazid_saad.Controller.OeuvreControler;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
//import net.proteanit.sql.DbUtils;


/**
 *
 * @author dizay
 */
public class IHMoeuvre extends javax.swing.JFrame {

    /**
     * Creates new form IHMusager
     */
    OeuvreControler  oc=new OeuvreControler (); 
   
    
    public IHMoeuvre() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titre = new javax.swing.JTextField();
        auteur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        L2 = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        Bsupp = new javax.swing.JButton();
        vd = new javax.swing.JButton();
        L1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Typee = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableOeuvre = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        NomForSearch = new javax.swing.JLabel();
        Titrech = new javax.swing.JTextField();
        Blist = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ajouter Oeuvre");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titre");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Auteur");

        titre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        titre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                titreKeyTyped(evt);
            }
        });

        auteur.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        auteur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auteurKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lending");

        L2.setEditable(false);
        L2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                L2KeyTyped(evt);
            }
        });

        ajouter.setBackground(new java.awt.Color(0, 0, 0));
        ajouter.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        ajouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ajouterKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ajouterKeyReleased(evt);
            }
        });

        Bsupp.setBackground(new java.awt.Color(0, 0, 0));
        Bsupp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Bsupp.setForeground(new java.awt.Color(255, 255, 255));
        Bsupp.setText("Supprimer");
        Bsupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsuppActionPerformed(evt);
            }
        });
        Bsupp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BsuppKeyPressed(evt);
            }
        });

        vd.setBackground(new java.awt.Color(0, 0, 0));
        vd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vd.setForeground(new java.awt.Color(255, 255, 255));
        vd.setText("Vider Les Champs");
        vd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdActionPerformed(evt);
            }
        });

        L1.setEditable(false);
        L1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                L1KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lending2");

        Typee.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Typee.setForeground(new java.awt.Color(51, 51, 51));
        Typee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "noChoice", "Livre", "Magazine" }));
        Typee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TypeeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bsupp, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vd)
                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Typee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(L2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(L1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Typee)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vd)
                            .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bsupp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        TableOeuvre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableOeuvre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableOeuvre.setForeground(new java.awt.Color(102, 102, 102));
        TableOeuvre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titre", "Auteur", "NbrReservation", "Lending", "Lending2", "Type"
            }
        ));
        TableOeuvre.setGridColor(new java.awt.Color(255, 255, 255));
        TableOeuvre.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableOeuvre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableOeuvreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableOeuvre);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch.setText("Titre");

        Titrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TitrechKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TitrechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TitrechKeyTyped(evt);
            }
        });

        Blist.setBackground(new java.awt.Color(0, 0, 0));
        Blist.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist.setForeground(new java.awt.Color(255, 255, 255));
        Blist.setText("Lister Tout");
        Blist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlistActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identifier Oeuvre");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vider Le Tableau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titrech, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Blist, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(476, 476, 476))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Titrech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Blist, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
       
         if(titre.getText().equals("") || auteur.getText().equals("") || L1.getText().equals("") || L2.getText().equals("")|| Typee.getSelectedItem()=="noChoice"){
             JOptionPane.showMessageDialog(null, "Remplir Tous Les Champs Avant Ajouter","Erreur",JOptionPane.ERROR_MESSAGE);
             JOptionPane.showMessageDialog(null, "Veuillez Choisir Un Type","Erreur",JOptionPane.ERROR_MESSAGE);
         }
         else{
             
        
        oc.AjouterOeuvre(titre.getText(),auteur.getText(),Integer.parseInt(L1.getText()),Integer.parseInt(L2.getText()) , Typee.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null, "Ajout Avec Succés","OK",JOptionPane.INFORMATION_MESSAGE);
        
        oc.Lister();
          viderr();
         
         
         
         }
         
    }//GEN-LAST:event_ajouterActionPerformed

    private void BlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlistActionPerformed
        // TODO add your handling code here:
        
        oc.Lister();
        TableOeuvre.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
      
    }//GEN-LAST:event_BlistActionPerformed

    private void TableOeuvreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableOeuvreMouseClicked
        // TODO add your handling code here:
        try {
            int row=TableOeuvre.getSelectedRow();
            String Table_click=(TableOeuvre.getModel().getValueAt(row, 0).toString());
            
             String sql="select * from oeuvre where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);
            
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("Titre");
                titre.setText(add1);
                String add2=DbInteraction.rs.getString("Auteur");
                auteur.setText(add2);
                String add3=DbInteraction.rs.getString("Lending");
                L1.setText(add3);
                String add4= DbInteraction.rs.getString("Lending2");
                L2.setText(add4);
                String add5= DbInteraction.rs.getString("Discriminator");//new SimpleDateFormat("yyyy-MM-dd").parse(Table_click);
                Typee.setSelectedItem(add5);
               
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_TableOeuvreMouseClicked
        public void videtable(){
            DefaultTableModel dm = (DefaultTableModel) TableOeuvre.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }

        }  
    private void TitrechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyReleased
        // TODO add your handling code here:
        
        
        oc.FindByTitle(Titrech.getText());
        TableOeuvre.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        
        // if(Nomrech.getText().equals("")){
        //     videtable();
        // }
       
   
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){
         
                videtable();
            
    }
         
    }//GEN-LAST:event_TitrechKeyReleased
public  void viderr(){
        titre.setText("");
        auteur.setText("");
        Typee.setSelectedItem("");
        L1.setText("");
        L2.setText("");
}
    private void BsuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsuppActionPerformed
        // TODO add your handling code here:
     
         
        int row=IHMoeuvre.TableOeuvre.getSelectedRow();
        String ID=(TableOeuvre.getModel().getValueAt(row, 0).toString());
         oc.SupprimerOeuvre(titre.getText());
  
         JOptionPane.showMessageDialog(null, "Suppression Avec Succés");
         oc.Lister();
        viderr();
        
        
        
    }//GEN-LAST:event_BsuppActionPerformed

    private void L2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L2KeyTyped
        // TODO add your handling code her 
    }//GEN-LAST:event_L2KeyTyped

    private void titreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == KeyEvent.VK_SPACE) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
          
    }//GEN-LAST:event_titreKeyTyped

    private void auteurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auteurKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
          
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c == KeyEvent.VK_SPACE) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
    }//GEN-LAST:event_auteurKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
          
            
    
    }//GEN-LAST:event_formWindowActivated

    private void TitrechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
          char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z'|| c == KeyEvent.VK_SPACE) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
              
                
              
    }//GEN-LAST:event_TitrechKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        videtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdActionPerformed
        // TODO add your handling code here:
        viderr();
    }//GEN-LAST:event_vdActionPerformed

    private void TitrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TitrechKeyPressed

    private void BsuppKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BsuppKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_BsuppKeyPressed

    private void ajouterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ajouterKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ajouterKeyReleased

    private void ajouterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ajouterKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ajouterKeyPressed

    private void L1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_L1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_L1KeyTyped

    private void TypeeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TypeeItemStateChanged
        // TODO add your handling code here:
        if(Typee.getSelectedItem()=="Livre"){
            L2.setText("30");
            L1.setText("0");
        }
        if(Typee.getSelectedItem()=="Magazine"){
            L1.setText("10");
            L2.setText("0");
        }
        if(Typee.getSelectedItem()=="noChoice"){
            L1.setText("0");
            L2.setText("0");
        }
        
    }//GEN-LAST:event_TypeeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMoeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMoeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMoeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMoeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMoeuvre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blist;
    private javax.swing.JButton Bsupp;
    private javax.swing.JTextField L1;
    private javax.swing.JTextField L2;
    private javax.swing.JLabel NomForSearch;
    private static javax.swing.JTable TableOeuvre;
    private javax.swing.JTextField Titrech;
    private javax.swing.JComboBox<String> Typee;
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField auteur;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField titre;
    private javax.swing.JButton vd;
    // End of variables declaration//GEN-END:variables

  
}
