/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibal_yazid_saad.View;

import bibal_yazid_saad.Connection.DbInteraction;
import bibal_yazid_saad.Controller.UsagerControler;
import static bibal_yazid_saad.Connection.DbInteraction.st;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import net.proteanit.sql.DbUtils;


/**
 *
 * @author dizay
 */
public class IHMusager extends javax.swing.JFrame {

    /**
     * Creates new form IHMusager
     */
    UsagerControler  uc=new UsagerControler(); 
    
    public IHMusager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ajouter = new javax.swing.JButton();
        Bsupp = new javax.swing.JButton();
        Bmodf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        adr = new javax.swing.JTextArea();
        vd = new javax.swing.JButton();
        dat = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableUsager = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        NomForSearch = new javax.swing.JLabel();
        Nomrech = new javax.swing.JTextField();
        Blist = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ajouter Usager");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom");

        nom.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });

        pre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                preKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adresse");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tel");

        tel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date_Naissance");

        ajouter.setBackground(new java.awt.Color(0, 0, 0));
        ajouter.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        ajouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ajouterKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ajouterKeyReleased(evt);
            }
        });

        Bsupp.setBackground(new java.awt.Color(0, 0, 0));
        Bsupp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Bsupp.setForeground(new java.awt.Color(255, 255, 255));
        Bsupp.setText("Supprimer");
        Bsupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsuppActionPerformed(evt);
            }
        });
        Bsupp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BsuppKeyPressed(evt);
            }
        });

        Bmodf.setBackground(new java.awt.Color(0, 0, 0));
        Bmodf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Bmodf.setForeground(new java.awt.Color(255, 255, 255));
        Bmodf.setText("Modifier");
        Bmodf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodfActionPerformed(evt);
            }
        });

        adr.setColumns(20);
        adr.setRows(5);
        jScrollPane3.setViewportView(adr);

        vd.setBackground(new java.awt.Color(0, 0, 0));
        vd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vd.setForeground(new java.awt.Color(255, 255, 255));
        vd.setText("Vider Les Champs");
        vd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bsupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bmodf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(51, 51, 51)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 9, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(vd)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bmodf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bsupp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(4, 4, 4)
                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TableUsager.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableUsager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableUsager.setForeground(new java.awt.Color(102, 102, 102));
        TableUsager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Date_Naissance", "Tel", "Adresse"
            }
        ));
        TableUsager.setGridColor(new java.awt.Color(255, 255, 255));
        TableUsager.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableUsager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUsagerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableUsager);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch.setText("Nom");

        Nomrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomrechKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomrechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomrechKeyTyped(evt);
            }
        });

        Blist.setBackground(new java.awt.Color(0, 0, 0));
        Blist.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist.setForeground(new java.awt.Color(255, 255, 255));
        Blist.setText("Lister Tout");
        Blist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlistActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identifier Usager");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vider Le Tableau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nomrech, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Blist, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nomrech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Blist, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
       
         if(nom.getText().equals("") || pre.getText().equals("") || tel.getText().equals("") || adr.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Remplir Tous Les Champs Avant Ajouter","Erreur",JOptionPane.ERROR_MESSAGE);
            
              //if (tel.getText().length()==10){
               // JOptionPane.showMessageDialog(null, "Entrer Un Nombre","Erreur",JOptionPane.ERROR_MESSAGE);
               // }
         }
         else{
             
        
        uc.ajouterUsager(nom.getText(),pre.getText(), convertUtilDateToSqlDate(dat.getDate()),tel.getText() , adr.getText());
        JOptionPane.showMessageDialog(null, "Ajout Avec Succés","OK",JOptionPane.INFORMATION_MESSAGE);
        
        uc.Lister();
          viderr();
         
         
         
         }
         
    }//GEN-LAST:event_ajouterActionPerformed

    private void BlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlistActionPerformed
        // TODO add your handling code here:
        
        uc.Lister();
      
    }//GEN-LAST:event_BlistActionPerformed

    private void TableUsagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsagerMouseClicked
        // TODO add your handling code here:
        try {
            int row=TableUsager.getSelectedRow();
            String Table_click=(TableUsager.getModel().getValueAt(row, 0).toString());
            
             String sql="select * from usager where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);
            
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("Nom");
                nom.setText(add1);
                String add2=DbInteraction.rs.getString("Prenom");
                pre.setText(add2);
                String add3=DbInteraction.rs.getString("Tel");
                tel.setText(add3);
                String add4=DbInteraction.rs.getString("Adresse");
                adr.setText(add4);
                Date date= DbInteraction.rs.getDate("Date_Naissance");//new SimpleDateFormat("yyyy-MM-dd").parse(Table_click);
                dat.setDate(date);
               
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_TableUsagerMouseClicked
        public void videtable(){
            DefaultTableModel dm = (DefaultTableModel) TableUsager.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }

        }  
    private void NomrechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyReleased
        // TODO add your handling code here:
        
        
        uc.FindByName(Nomrech.getText());
        
        // if(Nomrech.getText().equals("")){
        //     videtable();
        // }
       
   
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){
         
                videtable();
            
    }
         
    }//GEN-LAST:event_NomrechKeyReleased
public  void viderr(){
      nom.setText("");
        pre.setText("");
        dat.setDate(null);
        adr.setText("");
        tel.setText("");
}
    private void BsuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsuppActionPerformed
        // TODO add your handling code here:
     
         
        
         uc.SupprimerUsager(nom.getText());
  
         JOptionPane.showMessageDialog(null, "Suppression Avec Succés");
         uc.Lister();
        viderr();
        
        
        
    }//GEN-LAST:event_BsuppActionPerformed

    private void BmodfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodfActionPerformed
        // TODO add your handling code here:
        
        uc.ModifierUsager(nom.getText(),pre.getText(), convertUtilDateToSqlDate(dat.getDate()),tel.getText() , adr.getText());
        
         JOptionPane.showMessageDialog(null, "Modification Avec Succés");
         viderr();
         uc.Lister();
      
       
    }//GEN-LAST:event_BmodfActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        // TODO add your handling code her
          
           char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= '0' && c <= '9') {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
          
           int len=tel.getText().length();
 
                if (len>=15) {
                     evt.consume();  
                }
               
              
          
          
    }//GEN-LAST:event_telKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' ) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
          
    }//GEN-LAST:event_nomKeyTyped

    private void preKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_preKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
          
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' ) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
    }//GEN-LAST:event_preKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tel.setText("+(212)");
          
            
    
    }//GEN-LAST:event_formWindowActivated

    private void NomrechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
          char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' ) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
              
                
              
    }//GEN-LAST:event_NomrechKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        videtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdActionPerformed
        // TODO add your handling code here:
        viderr();
    }//GEN-LAST:event_vdActionPerformed

    private void NomrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NomrechKeyPressed

    private void BsuppKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BsuppKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_BsuppKeyPressed

    private void ajouterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ajouterKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ajouterKeyReleased

    private void ajouterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ajouterKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ajouterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMusager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMusager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMusager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMusager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMusager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blist;
    private javax.swing.JButton Bmodf;
    private javax.swing.JButton Bsupp;
    private javax.swing.JLabel NomForSearch;
    private javax.swing.JTextField Nomrech;
    public static javax.swing.JTable TableUsager;
    private javax.swing.JTextArea adr;
    private javax.swing.JButton ajouter;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pre;
    private javax.swing.JTextField tel;
    private javax.swing.JButton vd;
    // End of variables declaration//GEN-END:variables

  public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
   
      
      
      
      if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Enter Une Date De Naissance","Erreur",JOptionPane.ERROR_MESSAGE);
    }
    return null;
}
}
